/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import modelo.bean.Aluno;
import modelo.dao.AlunoDAO;
import java.awt.Image;
import java.awt.Toolkit;



/**
 *
 * @author ldabr
 */
public class TelaAlunos extends javax.swing.JInternalFrame {

    static int idAluno;
    static String nome;
    static boolean preecamp; 
    
    
    public TelaAlunos() {
        
        initComponents();
        
        DefaultTableModel modelo = (DefaultTableModel) jTblAlunos.getModel();
        jTblAlunos.setRowSorter(new TableRowSorter(modelo));
        
        readJTblAluno();
    }

    public void readJTblAluno(){
        DefaultTableModel modelo = (DefaultTableModel) jTblAlunos.getModel();
        modelo.setNumRows(0);
        AlunoDAO adao = new AlunoDAO();
        
        for(Aluno a: adao.read()){     
            modelo.addRow(new Object[]{
                a.getId(),
                a.getNome(),
                a.getSexo(),
                a.getDatanasc(),
                a.getObjetivo()
            });
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTblAlunos = new javax.swing.JTable();
        jBtnEditar = new javax.swing.JButton();
        jTxtIdAluno = new javax.swing.JTextField();
        jTxtNome = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(853, 624));

        jTblAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Sexo", "Data Nascimento", "Objetivo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTblAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblAlunosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTblAlunos);

        jBtnEditar.setText("Editar Treino");
        jBtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEditarActionPerformed(evt);
            }
        });

        jTxtIdAluno.setEditable(false);

        jTxtNome.setEditable(false);
        jTxtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtIdAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnEditar)
                    .addComponent(jTxtIdAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 411, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEditarActionPerformed
        if(jTblAlunos.getSelectedRow() != -1){
            // TODO add your handling code here:
            idAluno = Integer.parseInt(jTxtIdAluno.getText());
            nome = jTxtNome.getText();
            preecamp = true;
            
            TelaAlunoTreino alunotreino = new TelaAlunoTreino();
            alunotreino.setVisible(true);
            
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um aluno.");
        }
    }//GEN-LAST:event_jBtnEditarActionPerformed

    private void jTblAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblAlunosMouseClicked
        int linha = jTblAlunos.getSelectedRow();

        /* Verifica se não foi clicado em uma tabela vazia */
        if (linha > -1) {
            /* Captura o modelo da tabela */
            DefaultTableModel modelo = (DefaultTableModel) jTblAlunos.getModel();

            /* Copia os dados do registro selecionado para os campos texto */
            jTxtIdAluno.setText(modelo.getValueAt(linha, 0).toString());
            jTxtNome.setText(modelo.getValueAt(linha, 1).toString());

        }
    }//GEN-LAST:event_jTblAlunosMouseClicked

    private void jTxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnEditar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblAlunos;
    private javax.swing.JTextField jTxtIdAluno;
    private javax.swing.JTextField jTxtNome;
    // End of variables declaration//GEN-END:variables

}
