
package telas;

import static javafx.beans.binding.Bindings.or;
import static javax.management.Query.or;
import javax.swing.table.DefaultTableModel;
import Conexao.Conexao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.bean.Exercicio;
import modelo.bean.Treino;
import modelo.bean.Treino_exercicio;
import modelo.dao.ExercicioDAO;
import modelo.dao.TreinoDAO;
import modelo.dao.Treino_exercicioDAO;


public class TelaTreinos extends javax.swing.JInternalFrame {

    
    public TelaTreinos(){
        initComponents();
       
        
        ExercicioDAO edao = new ExercicioDAO();
        TreinoDAO tdao = new TreinoDAO();
        
        
        for (Treino t: tdao.read()){
            jCbTreino.addItem(t);
        }
        
        for (Exercicio e: edao.read()){
            jCbEx.addItem(e);
        }
        
        readJTbl();
  
    }
    
    public void readJTbl(){
        
        
        DefaultTableModel tabelaA = (DefaultTableModel) jTblA.getModel();
        tabelaA.setNumRows(0);
        DefaultTableModel tabelaB = (DefaultTableModel) jTblB.getModel();
        tabelaB.setNumRows(0);
        DefaultTableModel tabelaC = (DefaultTableModel) jTblC.getModel();
        tabelaC.setNumRows(0);
        DefaultTableModel tabelaD = (DefaultTableModel) jTblD.getModel();
        tabelaD.setNumRows(0);
        DefaultTableModel tabelaE = (DefaultTableModel) jTblE.getModel();
        tabelaE.setNumRows(0);
        DefaultTableModel tabelaF = (DefaultTableModel) jTblF.getModel();
        tabelaF.setNumRows(0);
          
        Exercicio e = new Exercicio();
        
        String nome;
        
        Treino_exercicioDAO tedao = new Treino_exercicioDAO();
        
        Treino treino = (Treino) jCbTreino.getSelectedItem();
        
        
        
        for(Treino_exercicio te: tedao.readA()){ 

 
                if(treino.getId() == te.getFk_id_treinos()){
                    
                    tabelaA.addRow(new Object[]{
                        te.getId(),
                        te.getExercicio(),
                        te.getSerie(),
                        te.getRepeticao(),
                        te.getDivisao()
                    });
                }
            
        }
        
        for(Treino_exercicio te: tedao.readB()){  
                if(treino.getId() == te.getFk_id_treinos()){
                    tabelaB.addRow(new Object[]{
                        te.getId(),
                        te.getExercicio(),
                        te.getSerie(),
                        te.getRepeticao(),
                        te.getDivisao()
                    });
                }
        }
        
        for(Treino_exercicio te: tedao.readC()){  
                if(treino.getId() == te.getFk_id_treinos()){
                    tabelaC.addRow(new Object[]{
                        te.getId(),
                        te.getExercicio(),
                        te.getSerie(),
                        te.getRepeticao(),
                        te.getDivisao()
                    });
                }
        }
        
        for(Treino_exercicio te: tedao.readD()){  
                if(treino.getId() == te.getFk_id_treinos()){
                    tabelaD.addRow(new Object[]{
                        te.getId(),
                        te.getExercicio(),
                        te.getSerie(),
                        te.getRepeticao(),
                        te.getDivisao()
                    });
                }
        }
        
        for(Treino_exercicio te: tedao.readE()){  
                if(treino.getId() == te.getFk_id_treinos()){
                    tabelaE.addRow(new Object[]{
                        te.getId(),
                        te.getExercicio(),
                        te.getSerie(),
                        te.getRepeticao(),
                        te.getDivisao()
                    });
                }
        }
        
        for(Treino_exercicio te: tedao.readF()){  
                if(treino.getId() == te.getFk_id_treinos()){
                    tabelaF.addRow(new Object[]{
                        te.getId(),
                        te.getExercicio(),
                        te.getSerie(),
                        te.getRepeticao(),
                        te.getDivisao()
                    });
                }
        }
        
    }
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtSerie = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedA = new javax.swing.JTabbedPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTblA = new javax.swing.JTable();
        jTabbedB = new javax.swing.JTabbedPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTblB = new javax.swing.JTable();
        jTabbedC = new javax.swing.JTabbedPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTblC = new javax.swing.JTable();
        jTabbedD = new javax.swing.JTabbedPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTblD = new javax.swing.JTable();
        jTabbedE = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblE = new javax.swing.JTable();
        jTabbedF = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTblF = new javax.swing.JTable();
        jCbEx = new javax.swing.JComboBox<>();
        jTxtRepeticao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCbDivisao = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCbTreino = new javax.swing.JComboBox<>();
        jBtnAdicionar = new javax.swing.JButton();
        jBtnRemover = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(853, 624));

        jTblA.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Exercicio", "Series", "Repetição", "Divisão"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTblA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTblAMouseClicked(evt);
            }
        });
        jTblA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTblAKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(jTblA);

        jTabbedA.addTab("A", jScrollPane3);

        jTabbedPane1.addTab("A", jTabbedA);

        jTblB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Exercicio", "Series", "Repetição", "Divisão"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTblB);

        jTabbedB.addTab("B", jScrollPane4);

        jTabbedPane1.addTab("B", jTabbedB);

        jTblC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Exercicio", "Series", "Repetição", "Divisão"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTblC);

        jTabbedC.addTab("C", jScrollPane5);

        jTabbedPane1.addTab("C", jTabbedC);

        jTblD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Exercicio", "Series", "Repetição", "Divisão"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTblD);

        jTabbedD.addTab("D", jScrollPane6);

        jTabbedPane1.addTab("D", jTabbedD);

        jTblE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Exercicio", "Series", "Repetição", "Divisão"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTblE);

        jTabbedE.addTab("E", jScrollPane1);

        jTabbedPane1.addTab("E", jTabbedE);

        jTblF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Exercicio", "Series", "Repetição", "Divisão"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTblF);

        jTabbedF.addTab("F", jScrollPane2);

        jTabbedPane1.addTab("F", jTabbedF);

        jCbEx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECIONAR" }));

        jLabel1.setText("Exercicio");

        jLabel2.setText("Series");

        jLabel3.setText("Repetição");

        jCbDivisao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "A", "B", "C", "D", "E", "F", " " }));

        jLabel4.setText("Divisão");

        jLabel5.setText("Treino");

        jCbTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbTreinoActionPerformed(evt);
            }
        });

        jBtnAdicionar.setText("Adicionar");
        jBtnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAdicionarActionPerformed(evt);
            }
        });

        jBtnRemover.setText("Remover");
        jBtnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCbEx, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTxtSerie)
                    .addComponent(jTxtRepeticao)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jCbTreino, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCbDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnAdicionar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnRemover)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCbTreino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCbEx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTxtRepeticao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCbDivisao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAdicionar)
                    .addComponent(jBtnRemover))
                .addGap(0, 93, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAdicionarActionPerformed
        Treino_exercicio te = new Treino_exercicio();
        Treino_exercicioDAO dao = new Treino_exercicioDAO();
        
        Treino treino = (Treino) jCbTreino.getSelectedItem();
        Exercicio exercicio = (Exercicio) jCbEx.getSelectedItem();
  
        te.setFk_id_treinos(treino.getId());
        te.setFk_id_exercicio(exercicio.getId());
        te.setExercicio(exercicio.getNome());
        te.setSerie(jTxtSerie.getText());
        te.setRepeticao(jTxtRepeticao.getText());
        te.setDivisao((String) jCbDivisao.getSelectedItem());

        dao.create(te);

        jTxtSerie.setText("");
        jTxtRepeticao.setText("");
        jCbEx.setSelectedItem("SELECIONAR");
        jCbDivisao.setSelectedItem(" ");

        readJTbl();  
        
    }//GEN-LAST:event_jBtnAdicionarActionPerformed

    private void jCbTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbTreinoActionPerformed
       
            readJTbl();
  
    }//GEN-LAST:event_jCbTreinoActionPerformed

    private void jBtnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnRemoverActionPerformed
        if(jTblA.getSelectedRow() != -1){

            Treino_exercicio te = new Treino_exercicio();
            Treino_exercicioDAO tedao = new Treino_exercicioDAO();

            te.setId((int)jTblA.getValueAt(jTblA.getSelectedRow(), 0));
            tedao.delete(te);

            readJTbl();
        }else{
            if(jTblB.getSelectedRow() != -1){

                Treino_exercicio te = new Treino_exercicio();
                Treino_exercicioDAO tedao = new Treino_exercicioDAO();

                te.setId((int)jTblB.getValueAt(jTblB.getSelectedRow(), 0));
                tedao.delete(te);

                readJTbl();
            }else{
                if(jTblC.getSelectedRow() != -1){

                    Treino_exercicio te = new Treino_exercicio();
                    Treino_exercicioDAO tedao = new Treino_exercicioDAO();

                    te.setId((int)jTblC.getValueAt(jTblC.getSelectedRow(), 0));
                    tedao.delete(te);

                    readJTbl();
                }else{
                    if(jTblD.getSelectedRow() != -1){

                        Treino_exercicio te = new Treino_exercicio();
                        Treino_exercicioDAO tedao = new Treino_exercicioDAO();

                        te.setId((int)jTblD.getValueAt(jTblD.getSelectedRow(), 0));
                        tedao.delete(te);

                        readJTbl();
                    }else{
                        if(jTblE.getSelectedRow() != -1){

                            Treino_exercicio te = new Treino_exercicio();
                            Treino_exercicioDAO tedao = new Treino_exercicioDAO();

                            te.setId((int)jTblE.getValueAt(jTblE.getSelectedRow(), 0));
                            tedao.delete(te);

                            readJTbl();
                        }else{
                            if(jTblF.getSelectedRow() != -1){

                                Treino_exercicio te = new Treino_exercicio();
                                Treino_exercicioDAO tedao = new Treino_exercicioDAO();

                                te.setId((int)jTblF.getValueAt(jTblF.getSelectedRow(), 0));
                                tedao.delete(te);

                                readJTbl();
                            }else{
                                JOptionPane.showMessageDialog(null, "Selecione um item para remover.");
                            }

                        }
                    }
                }
            
            }
            
        }
   
    }//GEN-LAST:event_jBtnRemoverActionPerformed

    private void jTblAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTblAKeyReleased
    
    }//GEN-LAST:event_jTblAKeyReleased

    private void jTblAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblAMouseClicked

    }//GEN-LAST:event_jTblAMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAdicionar;
    private javax.swing.JButton jBtnRemover;
    private javax.swing.JComboBox<String> jCbDivisao;
    private javax.swing.JComboBox<Object> jCbEx;
    private javax.swing.JComboBox<Object> jCbTreino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTabbedPane jTabbedA;
    private javax.swing.JTabbedPane jTabbedB;
    private javax.swing.JTabbedPane jTabbedC;
    private javax.swing.JTabbedPane jTabbedD;
    private javax.swing.JTabbedPane jTabbedE;
    private javax.swing.JTabbedPane jTabbedF;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTblA;
    private javax.swing.JTable jTblB;
    private javax.swing.JTable jTblC;
    private javax.swing.JTable jTblD;
    private javax.swing.JTable jTblE;
    private javax.swing.JTable jTblF;
    private javax.swing.JTextField jTxtRepeticao;
    private javax.swing.JTextField jTxtSerie;
    // End of variables declaration//GEN-END:variables
}
